# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'matrices_verifing.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_admitance_impedance_verification(object):
    def setupUi(self, admitance_impedance_verification):
        admitance_impedance_verification.setObjectName("admitance_impedance_verification")
        admitance_impedance_verification.resize(994, 608)
        self.ybus = QtWidgets.QTableWidget(admitance_impedance_verification)
        self.ybus.setGeometry(QtCore.QRect(20, 70, 481, 231))
        self.ybus.setObjectName("ybus")
        self.ybus.setColumnCount(0)
        self.ybus.setRowCount(0)
        self.zbus = QtWidgets.QTableWidget(admitance_impedance_verification)
        self.zbus.setGeometry(QtCore.QRect(20, 330, 481, 231))
        self.zbus.setObjectName("zbus")
        self.zbus.setColumnCount(0)
        self.zbus.setRowCount(0)
        self.ybus_zbus = QtWidgets.QTableWidget(admitance_impedance_verification)
        self.ybus_zbus.setGeometry(QtCore.QRect(510, 70, 461, 491))
        self.ybus_zbus.setObjectName("ybus_zbus")
        self.ybus_zbus.setColumnCount(0)
        self.ybus_zbus.setRowCount(0)
        self.verify = QtWidgets.QPushButton(admitance_impedance_verification)
        self.verify.setGeometry(QtCore.QRect(20, 20, 951, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.verify.setFont(font)
        self.verify.setStyleSheet("QPushButton {\n"
"  background-color: #213f98;\n"
"  color: #fff;\n"
"  padding:5 px 5px;\n"
"  border: none;\n"
"  border-radius: 3px;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #2980b9;\n"
"}")
        self.verify.setObjectName("verify")
        self.label = QtWidgets.QLabel(admitance_impedance_verification)
        self.label.setGeometry(QtCore.QRect(30, 50, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(admitance_impedance_verification)
        self.label_2.setGeometry(QtCore.QRect(30, 310, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(admitance_impedance_verification)
        self.label_3.setGeometry(QtCore.QRect(520, 50, 141, 16))
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(admitance_impedance_verification)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 570, 951, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verified_or_not = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.verified_or_not.setFont(font)
        self.verified_or_not.setStyleSheet("QLable {\n"
"color: #213f98;\n"
"\n"
"}")
        self.verified_or_not.setText("")
        self.verified_or_not.setAlignment(QtCore.Qt.AlignCenter)
        self.verified_or_not.setObjectName("verified_or_not")
        self.horizontalLayout.addWidget(self.verified_or_not)

        self.retranslateUi(admitance_impedance_verification)
        QtCore.QMetaObject.connectSlotsByName(admitance_impedance_verification)

    def retranslateUi(self, admitance_impedance_verification):
        _translate = QtCore.QCoreApplication.translate
        admitance_impedance_verification.setWindowTitle(_translate("admitance_impedance_verification", "Verification"))
        self.verify.setText(_translate("admitance_impedance_verification", "Verify"))
        self.label.setText(_translate("admitance_impedance_verification", "Admitance matrix"))
        self.label_2.setText(_translate("admitance_impedance_verification", "Impedance matrix"))
        self.label_3.setText(_translate("admitance_impedance_verification", "Admitance - Impedance"))
